config/routes.rb
Rails.application.routes.draw do
   resources :books
  root to: 'books#root'
  patch 'edit'=>'books#edit'
post '/books/:id/'=>'books#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true

  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books=Book.all
    @book=Book.new
  end

  def show
    @book=Book.find(params[:id])
  end

  def create
     @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
      @books=Book.all
      render :index
    end
  end

  def edit
    @book=Book.find(params[:id])
  end

  def destroy
     book=Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
      @books=Book.all
      render :edit
    end
  end

   private
   def book_params
    params.require(:book).permit(:title, :body)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1><strong>Editing Book</strong></h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %> error prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model:@book,local:true do |f| %>
<div class="edit-top"><h4>Title</h4>
 <%= f.text_field :title %>
<h4>Bodyy</h4>
 <%= f.text_area :body %>
 <div class="edit-update"><%= f.submit 'Update Book' %></div>

<%= link_to "Show", book_path(@book.id) %>
  |
 <%= link_to "Back", books_path %>

 </div>
 <% end %>

app/views/books/index.html.erb
<h1><strong>Books</strong></h1>
<div class="index-top">
<div class="index-title"><strong>Title</strong></div>
<div class="index-body"><strong>Body</strong></div>
</div>
<% @books.each do |book| %>
<table cellspacing="20">
<tr>
  <td><div class="index-title-item"><%= book.title %></td></div>
  <td><div class="index-body-item"><%= book.body %></td></div>
  <td><%=link_to "Show",book_path(book.id) %></td>
  <td><%=link_to "Edit",edit_book_path(book.id) %></td>
  <td><%= link_to "Destroy",book_path(book.id), method: :delet,"data-confirm" => "本当に削除しますか？"  %></td>
</tr>
</table>
<% end %>
<h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
  <% end %>
<!-- form_with部分 -->
<%= form_with model:@book, local:true do |f| %>

  <h4><strong>Title</strong></h4>
  <%= f.text_field :title %>

  <h4><strong>Body</strong></h4>
  <%= f.text_area :body %>

 <div> <%= f.submit 'Create Book' %></div>

<% end %>

app/views/books/root.html.erb
<h1>
  ようこそ<strong>Bookers</strong>へ！
</h1>
<p><strong>Bookers</strong>では、さまざな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><%= link_to "start", books_path %></p>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<%= form_with model: @book,  local:true do |book| %>
<div class="show-title"><p><strong>Title:</strong></p>
<div class="show-titel-item"><%= @book.title %></div></div>
<div class="show-body"><p><strong>Body:</strong></p>
<div class="show-body-item"><%= @book.body %></div></div>
<div class="show-bottom"><%= link_to "Edit", edit_book_path(@book.id) %>
|
 <%= link_to "Back", books_path %></div>

 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= yield %>
  </body>
</html>